### ISSUE TITLE
resolver grpc-dns not working

### ISSUE THREAD

**Issue by zengzhengrong** [AlexCombat/consul-grpc-example#1]
Thank you repository, It's very helpful for me !
when I use grpc-dns it track the grpc error :

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1585188634.814721413","description":"Error received from peer ipv4:127.0.0.1:8600","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```
http and dns work fine

btw, consul.d/web.json
```
"http": "http://localhost:50052/test",
```
it should be /health

**Comment by almaslennikov** [comment]
Thank you for response.
[Here](https://github.com/AlexCombat/consul-grpc-example/blob/master/name_resolver.py#L43) I have left a comment explaining why grpc-dns resolver currently doesn't work. As far as I have dug out it's a problem on gRPC side as it should use another library underneath to resolve dns queries.

As for web.json config, I've been meaning to fix it, thanks
